### PR TITLE
Add message_serializer to initializer

### PR DESCRIPTION
**Pull request by scovetta**
The example doesn't work when the message_serializer is left off (Gremlin defaults this to GraphSONSerializersV3d0).

## Purpose

* Fix the sample code so it runs out of the box.

## Does this introduce a breaking change?
```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Get the code
```
git clone https://github.com/scovetta/azure-cosmos-db-graph-python-getting-started test
cd test
git checkout patch-1
[Update connect.py with your credentials, as per README.md]
```

* Test the code
```
Run `connect.py` as indicated within the README.md file.
```

## What to Check
Verify that the following are valid:
* Does the `connect.py` script complete as expected?

## Other Information
I'm not sure whether this is a bug/missing feature in the Gremlin client or the Cosmos DB backend.

### CODE REVIEW

**Comment by scovetta** [comment]
This fixes #7.

**Comment by LuisBosquez** [comment]
Hello @scovetta, what version of gremlinpython did you use for this? I am testing with gremlinpython 3.3.3 and it doesn't seem to have a serializer object defined.

**Comment by scovetta** [comment]
Hi @LuisBosquez It should be in [client.py](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/jython/gremlin_python/driver/client.py#L41), unless I'm using the wrong gremlinpython. The serializer I assign is defined in [serializers.py](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/jython/gremlin_python/driver/serializer.py#L149).

**Comment by LuisBosquez** [comment]
Tested and it works if you also add the import statement at the top:

`from gremlin_python.driver import serializer`

Could you add this change so I can merge it?

**Pull request merged**
